### PR TITLE
add return url, paymentmethods, channel and browserinfo as input in t…

### PR DESCRIPTION
**Pull request by meletios**
…he request

### CODE REVIEW

**Comment by meletios** [comment]
@palmenhq by while-list, do you mean a white-list? :D

**Comment by hedvigoscar** [comment]
This could be tricky for us on the native side as the return URL for us is entirely opaque and provided to us by the Adyen SDK.

I'm not opposed to it otherwise.

**Comment by palmenhq** [comment]
@meletios haha yes ofc
@hedvigoscar Maybe we can make out the host/protocol adyen sdk gives then?

**Comment by hedvigoscar** [comment]
We could try to reverse engineer it, but that could very well lead to issues down the line as this is fundamentally outside our control.

**Comment by hedvigoscar** [comment]
I suppose we could enforce a whitelist when the `WEB`-channel is active? 🤔

**Pull request merged**
